# Site settings
title: 梓匠輪輿
description: 'Persistance is Your Superiority' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://xingng.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/pi.svg"
logo-icon: "/assets/img/branding/pi.svg"
logo-icon-SEO: "/assets/img/branding/pi.svg" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/pi.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author:  梓匠輪輿
author-pic: pi.svg
about-author: I am an undergraduated student who favorite in learning and <br>studying mathematics and machine learning related topics. Due to the constraint of experience and time, if any correction available, please kindly contact me via email ngxing116@gmail.com. I will appreciate for your instruction.

# Contact links
email: ngxing116@gmail.com # Add your Email address
website: https://xingng.github.io # Add your website
github: xingng # Add your Github handle
gitalk:
    repo: xingng.github.io //  github 上博客仓库的名字
    client_id: 66e25f2fd51dfd824057 // Client ID
    client_secret: ea4c23c6750045379b53416c25090374ed033c87 // Client Secret

# Newsletter
mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Disqus
discus_identifier: xingng.github.io # Add your discus identifier
comments_curtain: yes # leave empty to show the disqus embed directly

# Tracker
analytics: G-R8SZS2YBZK
fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]